import {RegistrationState} from 'types';

const formFields = {
  email: {
    ru: {
      name: 'email',
      label: 'E-mail',
      type: 'email',
      placeholder: 'Адрес эл. почты',
      required: true,
    },
    en: {
      name: 'email',
      label: 'E-mail',
      type: 'email',
      placeholder: 'Email address',
      required: true,
    },
    ua: {
      name: 'email',
      label: 'E-mail',
      type: 'email',
      placeholder: 'Адреса ел. пошти',
      required: true,
    },
  },
};

export const initialState: RegistrationState = {
  isLoading: false,
  error: null,
  userData: {
    id: null,
    token: null,
    is_confirm_email: null,
    is_confirm_phone: null,
    is_profile_created: null,
    email: null,
    phone: null,
    password: null,
    lname: null,
    name: null,
    sname: null,
    birth_date: null,
    reset_password_token: null,
    confirm_phone_code: null,
    gender_id: null,
  },
  texts: {
    title: {
      ru: 'Войти в аккаунт',
      en: 'Sign In',
      ua: 'Увійти в обліковий запис',
    },
    intro: {
      ru: 'Введите ваш E-mail и пароль, чтобы начать использовать все преимущества платформы:',
      en: 'Enter your E-mail and password to start using all the advantages of the platform:',
      ua: 'Введіть ваш E-mail і пароль, щоб почати використовувати всі переваги платформи:',
    },
    successfulTitle: {
      ru: 'Аккаунт был успешно зарегистрирован.\n На ваш E-Mail отправлено письмо с ссылкой для подтверждения.',
      en: 'Account has been successfully registered.\n An email with a confirmation link has been sent to your E-mail.',
      ua: 'Аккаунт був успішно зареєстрований.\n На ваш E-Mail відправлено лист з посиланням для підтвердження.',
    },
    profileTitle: {
      ru: 'Регистрация пользователя',
      en: 'User Registration',
      ua: 'Реєстрація користувача',
    },
    profileIntro: {
      ru: 'Заполните информацию о себе, чтобы начать использовать все преимущества платформы',
      en: 'Fill in your information to start using all the advantages of the platform',
      ua: 'Заповніть інформацію про себе, щоб почати використовувати всі переваги платформи',
    },
    profileSuccessfulTitle: {
      ru: 'Новая компания успешно создана и добавлена в базу данных.\n Пройдите верификацию, чтобы завершить регистрацию компании.',
      en: 'The new company has been successfully created and added to the database.\n Complete the verification process to finalize company registration.',
      ua: 'Нову компанію успішно створено і додано до бази даних.\n Пройдіть верифікацію, щоб завершити реєстрацію компанії.',
    },
    verificationText: {
      ru: 'Пройти верификацию',
      en: 'Complete Verification',
      ua: 'Пройти верифікацію',
    },
    goToCompanyProfileText: {
      ru: 'Перейти в Профиль Компаний',
      en: 'Go to Company Profile',
      ua: 'Перейти до Профілю Компаній',
    },
  },
  lists: {
    advances: {
      ru: [
        {title: 'Автоматизация HR'},
        {title: 'Интеграция с job-порталами'},
        {title: 'Оценка персонала'},
        {title: 'Синхронизация с Outlook'},
        {title: 'Безопасность данных'},
        {title: 'Парсинг резюме'},
        {title: 'Мультиязычность'},
        {title: 'Конструктор отчетности'},
      ],
      en: [
        {title: 'HR Automation'},
        {title: 'Integration with job portals'},
        {title: 'Employee assessment'},
        {title: 'Outlook synchronization'},
        {title: 'Data security'},
        {title: 'Resume parsing'},
        {title: 'Multilingual support'},
        {title: 'Report builder'},
      ],
      ua: [
        {title: 'Автоматизація HR'},
        {title: 'Інтеграція з job-порталами'},
        {title: 'Оцінка персоналу'},
        {title: 'Синхронізація з Outlook'},
        {title: 'Захист даних'},
        {title: 'Аналіз резюме'},
        {title: 'Багатомовність'},
        {title: 'Конструктор звітів'},
      ],
    },
  },
  form: {
    buttonRegistration: {
      ru: 'Зарегистрироваться',
      en: 'Register',
      ua: 'Зареєструватися',
    },
    titleRegistration: {
      ru: 'Регистрация',
      en: 'Registration',
      ua: 'Реєстрація',
    },
    titleProfile: {
      ru: 'Профиль пользователя',
      en: 'User profile',
      ua: 'Профіль користувача',
    },
    titleAuthorization: {
      ru: 'Вход',
      en: 'Login',
      ua: 'Вхід',
    },
    titlePhoneVerification: {
      ru: 'Подтверждение телефона',
      en: 'Phone Verification',
      ua: 'Підтвердження телефону',
    },
    descriptionPhoneVerification: {
      ru: 'Мы отправили SMS с 6-значным кодом подтверждения на номер',
      en: 'We have sent an SMS with a 6-digit confirmation code to the number',
      ua: 'Ми відправили SMS з 6-значним кодом підтвердження на номер',
    },
    signInOption: {
      ru: 'Или войдите с помощью',
      en: 'Or sign in with',
      ua: 'Або увійдіть за допомогою',
    },
    buttonNext: {
      ru: 'Далее',
      en: 'Next',
      ua: 'Далі',
    },
    buttonExit: {
      ru: 'Выход',
      en: 'Exit',
      ua: 'Вихід',
    },
    buttonConfirmExit: {
      ru: 'Выйти',
      en: 'Logout',
      ua: 'Вийти',
    },
    buttonContinueExit: {
      ru: 'Продолжить',
      en: 'Continue',
      ua: 'Продовжити',
    },
    confirmLogout: {
      ru: 'Подтверждение выхода из аккаунта',
      en: 'Confirm Logout',
      ua: 'Підтвердження виходу з облікового запису',
    },
    logoutConfirmationMessage: {
      ru: 'Вы действительно хотите выйти из своей учетной записи?',
      en: 'Do you really want to log out of your account?',
      ua: 'Ви дійсно бажаєте вийти зі свого облікового запису?',
    },
    passwordMismatchErrorMessage: {
      ru: 'Новый пароль, который вы ввели, не совпадает!',
      en: 'The new password that you entered do not match!',
      ua: 'Новий пароль, який ви ввели, не співпадає!',
    },
    inputRequiredErrorMessage: {
      ru: 'Пожалуйста, введите ваш',
      en: 'Please input your',
      ua: 'Будь ласка, введіть ваш',
    },
    emailError: {
      ru: 'Неверный формат электронной почты!',
      en: 'Invalid email format!',
      ua: 'Невірний формат електронної пошти!',
    },
    passwordMinLengthRule: {
      en: 'Password must be at least 8 characters long.',
      ru: 'Длина пароля должна быть не менее 8 символов.',
      ua: 'Довжина пароля повинна бути не менше 8 символів.',
    },
    passwordMaxLengthRule: {
      en: 'Password must be no more than 14 characters long.',
      ru: 'Длина пароля должна быть не более 14 символов.',
      ua: 'Довжина пароля повинна бути не більше 14 символів.',
    },
    passwordFormatRule: {
      en: 'Password must contain Latin letters (A-z), Arabic numerals (0-9), and both lowercase and uppercase letters.',
      ru: 'Пароль должен состоять из букв латинского алфавита (A-z), арабских цифр (0-9). Буквенная часть пароля должна содержать как строчные, так и прописные (заглавные) буквы.',
      ua: 'Пароль повинен складатися з літер латинського алфавіту (A-z), арабських цифр (0-9). Літерна частина пароля повинна містити як малі, так і великі літери.',
    },
    phoneConfirmation: {
      ru: [
        {
          name: 'sms-code',
          label: 'SMS-код',
          type: 'text',
          placeholder: 'Укажите код',
          required: true,
        },
      ],
      en: [
        {
          name: 'sms-code',
          label: 'SMS Code',
          type: 'text',
          placeholder: 'Enter the code',
          required: true,
        },
      ],
      ua: [
        {
          name: 'sms-code',
          label: 'SMS-код',
          type: 'text',
          placeholder: 'Вкажіть код',
          required: true,
        },
      ],
    },
    registration: {
      ru: [
        formFields.email.ru,
        {
          name: 'password',
          label: 'Придумайте пароль',
          type: 'password',
          placeholder: 'Укажите ваш пароль',
          required: true,
        },
        {
          name: 'confirmPassword',
          label: 'Повторите пароль',
          type: 'password',
          placeholder: 'Повторите ваш пароль',
          required: true,
          dependencies: 'password',
        },
      ],
      en: [
        formFields.email.en,
        {
          name: 'password',
          label: 'Create Password',
          type: 'password',
          placeholder: 'Enter your password',
          required: true,
        },
        {
          name: 'confirmPassword',
          label: 'Confirm Password',
          type: 'password',
          placeholder: 'Confirm your password',
          required: true,
          dependencies: 'password',
        },
      ],
      ua: [
        formFields.email.ua,
        {
          name: 'password',
          label: 'Придумайте пароль',
          type: 'password',
          placeholder: 'Вкажіть ваш пароль',
          required: true,
        },
        {
          name: 'confirmPassword',
          label: 'Повторіть пароль',
          type: 'password',
          placeholder: 'Повторіть ваш пароль',
          required: true,
          dependencies: 'password',
        },
      ],
    },
    profile: {
      ru: [
        {
          name: 'sname',
          label: 'Фамилия',
          type: 'text',
          placeholder: 'Михайлов',
          required: true,
          width: '30%',
        },
        {
          name: 'name',
          label: 'Имя',
          type: 'text',
          placeholder: 'Михаил',
          required: true,
          width: '30%',
        },
        {
          name: 'lname',
          label: 'Отчество',
          type: 'text',
          placeholder: 'Михайлович',
          required: true,
          width: '30%',
        },
        {
          name: 'birth_date',
          label: 'Дата рождения',
          type: 'date',
          placeholder: '10/08/1983',
          required: true,
        },
        {
          name: 'gender_id',
          label: 'Пол',
          list: [
            {
              label: 'Мужчина',
              code: '1',
            },
            {
              label: 'Женщина',
              code: '2',
            },
            {
              label: 'Другой',
              code: '3',
            },
          ],
          type: 'select',
          placeholder: 'Выберите пол',
          required: true,
        },
        {
          name: 'phone',
          label: 'Телефон',
          type: 'phone',
          placeholder: '+38 (050) 725 60 09',
          required: true,
        },
        formFields.email.ru,
      ],
      en: [
        {
          name: 'sname',
          label: 'Last Name',
          type: 'text',
          placeholder: 'Smith',
          required: true,
          width: '30%',
        },
        {
          name: 'name',
          label: 'First Name',
          type: 'text',
          placeholder: 'John',
          required: true,
          width: '30%',
        },
        {
          name: 'lname',
          label: 'FatherName',
          type: 'text',
          placeholder: 'Michaelovich',
          required: true,
        },
        {
          name: 'birth_date',
          label: 'Date of Birth',
          type: 'date',
          placeholder: '08/10/1983',
          required: true,
        },
        {
          name: 'gender_id',
          label: 'Gender',
          list: [
            {
              label: 'Male',
              code: '1',
            },
            {
              label: 'Female',
              code: '2',
            },
            {
              label: 'Other',
              code: '3',
            },
          ],
          type: 'select',
          placeholder: 'Select gender',
          required: true,
        },
        {
          name: 'phone',
          label: 'Phone',
          type: 'phone',
          placeholder: '+38 (050) 725 60 09',
          required: true,
        },
        formFields.email.en,
      ],
      ua: [
        {
          name: 'sname',
          label: 'Прізвище',
          type: 'text',
          placeholder: 'Михайлов',
          required: true,
          width: '30%',
        },
        {
          name: 'name',
          label: "Ім'я",
          type: 'text',
          placeholder: 'Михайло',
          required: true,
          width: '30%',
        },
        {
          name: 'lname',
          label: 'По батькові',
          type: 'text',
          placeholder: 'Михайлович',
          required: true,
          width: '30%',
        },
        {
          name: 'birth_date',
          label: 'Дата народження',
          type: 'date',
          placeholder: '08/10/1983',
          required: true,
        },
        {
          name: 'gender_id',
          label: 'Стать',
          list: [
            {
              label: 'Чоловік',
              code: '1',
            },
            {
              label: 'Жінка',
              code: '2',
            },
            {
              label: 'Інше',
              code: '3',
            },
          ],
          type: 'select',
          placeholder: 'Виберіть стать',
          required: true,
        },
        {
          name: 'phone',
          label: 'Телефон',
          type: 'phone',
          placeholder: '+38 (050) 725 60 09',
          required: true,
        },
        formFields.email.ua,
      ],
    },
  },
};
